### ISSUE TITLE
userId para crear post/comment si hice Login

### ISSUE THREAD

**Issue by kalarconvl** [IIC3103-2024-01/help#12]
Hola!! Hice un login para que no se tenga que ingresar un id en el body en las requests de post/posts y post/comments. Cómo se va a corregir eso en el deploy del backend? Para el frontend funciona bien porque solo se puede crear un post o comment cuando estás loggeado, pero en el backend estoy enviando un error de "User not logged", lo puedo dejar así??

**Comment by kalarconvl** [comment]
Creo que no me deja agregar una etiqueta a la issue, no encuentro cómo hacerlo

**Comment by dedarritchon** [comment]
Hola @kalarconvl,

los endpoints del backend deben seguir estrictamente la documentación descrita en el enunciado, es decir, deben recibir el campo userId.

Saludos

**Comment by kalarconvl** [comment]
@dedarritchon pero en la [issue 6](https://github.com/IIC3103-2024-01/help/issues/6#issue-2214082228) indican que no es necesario pasarle el userId si es que se hace un login que almacene el current user
