### ISSUE TITLE
[T1] Duda sobre endpoints Obtener Usuarios, Posts y Comentarios

### ISSUE THREAD

**Issue by crow-rojas** [IIC3103-2024-01/help#2]
Hola, una consulta. En el enunciado los endpoints para obtener usuarios, posts y comentarios solo salen en su response como User[], Post[] y Comment[], pero, qué devolvemos exactamente?

Me imagino que para los Users y Posts, devolvemos una lista con todos los Usuarios y Posts, respectivamente. Pero para los Comentarios, como el endpoint recibe un `postId` como query parameter, se retorna una lista con todos los comentarios con ese `postId`, y no todos los comentarios de la base de datos.

Espero lo puedan aclarar, muchas gracias!

**Comment by dedarritchon** [comment]
Hola @crow-rojas,

La sintaxis `Objeto[]` es una forma de representar el tipo Lista de Objeto, es decir: `[Objeto, Objeto, ...]`. Otra forma comúnmente usada es `List<Object>`.

Los endpoints deben retornar una lista de los Usuarios, Posts y Comentarios creado hasta el momento, respectivamente.

En cuanto al _query parameter_ `postId` en el endpoint de obtener comentarios, no se va a revisar, por lo que queda opcional.
En ese sentido al mostrar los comentarios de un post tiene 2 opciones:

- Obtener todos los comentarios y filtrar a nivel de front
- Obtener los comentarios usando el parámetro `postId`, y obtener los comentarios de ese port ya filtrados.

De las dos formas pueden lograr el comportamiento esperado en el front. En el backend, solo se revisará la llamada sin indicar postId, es decir que retorne todos los comentarios creados hasta el momento (de todos los posts y de todos los usuarios)

Saludos,

Daniel
