### ISSUE TITLE
Servidor - Proyecto

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC3103-2024-01/help#32]
Hola, por lo que entendí del enunciado ustedes nos facilitaran un servidor para hacer el deploy del proyecto, ¿donde estan las
credenciales?, en el correo que enviaron solo me llego el token para consultar a la api.

Gracias.

**Comment by terelopezc** [comment]
Hola @Cadutodalcielo !
Hoydía se mandaron las credenciales por mail! Te deberían haber llegado las de tu grupo.
