### ISSUE TITLE
[Tarea 2] Linea de desplazamiento de trenes

### ISSUE THREAD

**Issue by kalarconvl** [IIC3103-2024-01/help#61]
Hola! El enunciado pide en los elementos mínimos: "Línea que muestre el desplazamiento realizado por cada tren, desde que el usuario se conecta al sitio". Esto ensucia mucho el mapa si salen todas al mismo tiempo. Hay que poner lineas sobre el mapa o agregar en la tabla las estaciones por las que ha pasado, o hay que agregar la linea de un tren solo si se aprieta sobre el tren? No entiendo bien este requerimiento. Tampoco encuentro este punto en la rúbrica de Canvas, es necesario agregarlas?

**Comment by dedarritchon** [comment]
Hola @kalarconvl ,
La trayectoria de los trenes no se va a considerar en la corrección, lo dejé comentado en esta [issue](https://github.com/IIC3103-2024-01/help/issues/62).
Saludos,
Daniel
