### ISSUE TITLE
Entrar al perfil de un usuario

### ISSUE THREAD

**Issue by SavkaAldunce** [IIC3103-2024-01/help#7]
Hola!

En la tarea debemos navegar únicamente en la pantalla de inicio mostrando todos los posts que existen o debemos implementar el poder entrar a un perfil y ver todos sus posts también?

**Comment by dedarritchon** [comment]
Hola @SavkaAldunce ,

Esto está detallado en [esta Issue](https://github.com/IIC3103-2024-01/help/issues/6),

Saludos
